<?php
$pageTitle = 'Contacto'; $activePage = 'contacto'; $basePath = '';
$firebaseAuthModule = false;
require_once __DIR__ . '/includes/auth.php';
$contactUser = currentUser();
$contactName = $contactUser !== null ? (string) ($contactUser['name'] ?? '') : '';
$contactEmail = $contactUser !== null ? (string) ($contactUser['email'] ?? '') : '';
require __DIR__ . '/includes/header.php'; require __DIR__ . '/includes/navbar.php';
?>
<main id="contenido"><section class="page-hero page-hero--compact"><div class="container"><span class="eyebrow eyebrow--light">Hablemos</span><h1>Estamos para <em>escucharte.</em></h1><p>Consultas comerciales, alianzas y experiencias CHICHEJ.</p></div></section><section class="section section--cream"><div class="container contact-layout"><div class="contact-copy"><span class="eyebrow">Contacto oficial</span><h2>Construyamos algo con sabor propio.</h2><p>Comunícate directamente con CHICHEJ o envíanos tu consulta mediante el formulario. Tu mensaje llegará al correo oficial de nuestro equipo.</p><div class="official-contacts"><a class="contact-channel" href="tel:+59173085467"><span>◎</span><div><small>Gerencia General</small><strong>73085467</strong><b>Llamar ahora →</b></div></a><a class="contact-channel contact-channel--whatsapp" href="https://wa.me/59177271557" target="_blank" rel="noopener noreferrer"><span>◉</span><div><small>WhatsApp CHICHEJ</small><strong>77271557</strong><b>Iniciar conversación →</b></div></a></div></div><form class="form-card" data-contact-form data-contact-endpoint="api/contact/send.php"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(chichejCsrfToken(), ENT_QUOTES, 'UTF-8') ?>"><label class="sr-only" aria-hidden="true">Sitio web<input type="text" name="website" tabindex="-1" autocomplete="off"></label><div class="form-row"><label>Nombre<input type="text" name="name" value="<?= htmlspecialchars($contactName, ENT_QUOTES, 'UTF-8') ?>" placeholder="Tu nombre" minlength="2" maxlength="80" autocomplete="name" required></label><label>Organización<input type="text" name="organization" placeholder="Empresa o institución" maxlength="120" autocomplete="organization"></label></div><label>Correo electrónico<input type="email" name="email" value="<?= htmlspecialchars($contactEmail, ENT_QUOTES, 'UTF-8') ?>" placeholder="nombre@ejemplo.com" maxlength="254" autocomplete="email" required></label><label>Motivo<select name="reason" required><option>Consulta general</option><option>Información comercial</option><option>Adquirir el sistema CHICHEJ</option><option>Alianza o distribución</option><option>Soporte</option></select></label><label>Mensaje<textarea name="message" rows="5" placeholder="Cuéntanos cómo podemos ayudarte" minlength="10" maxlength="4000" required></textarea></label><button class="button button--primary" type="submit" data-contact-submit>Enviar consulta <span>→</span></button><p class="form-status" data-contact-status role="status" aria-live="polite"></p></form></div></section></main>
<?php require __DIR__ . '/includes/footer.php'; ?>
