<?php
$pageTitle = 'Iniciar sesión'; $activePage = 'login'; $basePath = '';
require_once __DIR__ . '/includes/auth.php';
$firebaseConfig = require __DIR__ . '/config/firebase.php';
$authEnabled = $firebaseConfig['authentication_enabled'] === true;
$firebaseAuthModule = true;
$reason = $_GET['reason'] ?? '';
if (isAuthenticated()) {
    header('Location: ' . (isAdmin() ? 'admin/index.php' : 'usuario/index.php'), true, 302);
    exit;
}
require __DIR__ . '/includes/header.php'; require __DIR__ . '/includes/navbar.php';
?>
<main id="contenido" class="auth-page"><section class="auth-shell"><div class="auth-visual"><img src="assets/img/maserado3.jpeg" alt="Bebida CHICHEJ" loading="lazy"><div><span class="eyebrow eyebrow--light">Comunidad CHICHEJ</span><h1>Tu experiencia, en un solo lugar.</h1><p>La web utiliza la misma identidad y rol de la aplicación CHICHEJ.</p></div></div><div class="auth-panel"><a class="auth-back" href="index.php">← Volver al inicio</a><div class="auth-form-wrap"><span class="eyebrow">Bienvenido</span><h2>Inicia sesión</h2><?php if ($reason === 'authentication_required'): ?><div class="auth-message auth-message--warning" role="alert">Debes iniciar sesión para acceder a esa sección.</div><?php endif; ?><p>Acceso compartido con Firebase Authentication de CHICHEJ.</p><?php if (!$authEnabled): ?><div class="auth-message" role="status"><strong>Configuración del servidor incompleta</strong><span>El acceso permanece cerrado hasta disponer de la configuración pública Firebase y del verificador del servidor.</span></div><?php endif; ?><form class="form-card form-card--plain" data-auth-form data-session-endpoint="api/auth/session-login.php" aria-describedby="auth-status"><label>Correo electrónico<input type="email" name="email" placeholder="nombre@ejemplo.com" autocomplete="email" required <?= $authEnabled ? '' : 'disabled' ?>></label><label>Contraseña<span class="password-wrap"><input type="password" name="password" placeholder="Tu contraseña" autocomplete="current-password" required <?= $authEnabled ? '' : 'disabled' ?>><button type="button" data-password-toggle aria-label="Mostrar contraseña" <?= $authEnabled ? '' : 'disabled' ?>>Ver</button></span></label><div class="form-options"><label class="check"><input type="checkbox" name="remember" <?= $authEnabled ? '' : 'disabled' ?>> Mantener sesión iniciada</label><a href="#recuperar-clave">Olvidé mi contraseña</a></div><button class="button button--primary button--full" type="submit" data-auth-submit <?= $authEnabled ? '' : 'disabled' ?>><span data-auth-submit-label>Ingresar</span> <span aria-hidden="true">→</span></button><p class="form-status" id="auth-status" role="status" aria-live="polite"></p></form><form class="password-recovery" id="recuperar-clave" data-password-recovery-form><label>Correo de tu cuenta<input type="email" name="recovery_email" autocomplete="email" placeholder="nombre@ejemplo.com" required <?= $authEnabled ? '' : 'disabled' ?>></label><button class="text-link" type="submit" <?= $authEnabled ? '' : 'disabled' ?>>Enviar enlace de recuperación</button><p class="form-status" data-password-recovery-status role="status" aria-live="polite"></p></form><p class="auth-switch">¿Aún no tienes cuenta? <a href="registro.php">Crear cuenta</a></p></div></div></section></main>
<?php require __DIR__ . '/includes/footer.php'; ?>
