<?php
$pageTitle = 'Nosotros'; $activePage = 'nosotros'; $basePath = '';
require __DIR__ . '/includes/header.php'; require __DIR__ . '/includes/navbar.php';
?>
<main id="contenido">
    <section class="page-hero page-hero--story"><div class="container"><span class="eyebrow eyebrow--light">Nuestra historia</span><h1>Tradición que <em>fermenta futuro.</em></h1><p>Una marca boliviana que transforma herencia, sabor e innovación en una experiencia contemporánea.</p></div></section>
    <section class="section section--cream"><div class="container split"><div class="story-visual reveal"><img src="assets/img/maserado2.jpeg" alt="Presentación institucional de CHICHEJ" loading="lazy"></div><div class="section-copy reveal"><span class="eyebrow">Quiénes somos</span><h2>Una identidad que se comparte.</h2><p class="lead">CHICHEJ nace del encuentro entre la riqueza de nuestras bebidas tradicionales y el deseo de hacerlas accesibles a nuevas generaciones.</p><p>Esta plataforma prepara el camino para conectar a clientes, productos, reservas y dispensadores en un solo lugar, manteniendo siempre una voz auténtica y cercana.</p></div></div></section>
    <section class="section"><div class="container"><div class="section-heading"><div><span class="eyebrow">Nuestro compromiso</span><h2>Principios que nos mueven.</h2></div></div><div class="value-grid"><article><span>01</span><h3>Origen</h3><p>Reconocer y valorar el conocimiento que hace única nuestra bebida.</p></article><article><span>02</span><h3>Calidad</h3><p>Construir una experiencia consistente en cada presentación y canal.</p></article><article><span>03</span><h3>Innovación</h3><p>Usar la tecnología para acercar el producto sin perder su esencia.</p></article></div></div></section>
    <section class="section section--cream expo-section" id="feria-chelito-2026"><div class="container expo-card reveal"><div class="expo-card__identity"><span class="eyebrow eyebrow--light">Participación institucional</span><strong>13va.</strong><small>Expo Feria</small><div class="expo-card__year">2026</div></div><div class="expo-card__content"><span class="eyebrow">Proyecto CHICHEJ</span><h2>Expo Feria Chelito Quiroga 2026</h2><p class="lead">Instituto Tecnológico Marcelo Quiroga Santa Cruz</p><p>Carrera de Sistemas Informáticos</p><div class="expo-ready-grid"><span>Fotografías</span><span>Videos</span><span>Demostración</span><span>Tríptico digital</span><span>QR</span><span>Documentación pública</span></div><p class="expo-note">Sección preparada para incorporar material oficial cuando esté disponible.</p></div></div></section>
</main>
<?php require __DIR__ . '/includes/footer.php'; ?>
