<?php
declare(strict_types=1);
use Kreait\Firebase\Exception\Auth\FailedToVerifyToken;use Kreait\Firebase\Factory;
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
function registrationJson(int $status,array $payload):never{http_response_code($status);echo json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if(($_SERVER['REQUEST_METHOD']??'')!=='POST'){header('Allow: POST');registrationJson(405,['success'=>false,'code'=>'method_not_allowed']);}
if(strtolower(trim(explode(';',$_SERVER['CONTENT_TYPE']??'')[0]))!=='application/json')registrationJson(415,['success'=>false,'code'=>'json_required']);
$raw=file_get_contents('php://input');if(!is_string($raw)||$raw===''||strlen($raw)>32768)registrationJson(400,['success'=>false,'code'=>'invalid_request']);
try{$body=json_decode($raw,true,4,JSON_THROW_ON_ERROR);}catch(JsonException){registrationJson(400,['success'=>false,'code'=>'invalid_json']);}
if(!is_array($body)||array_keys($body)!==['csrf_token','idToken','nombre'])registrationJson(400,['success'=>false,'code'=>'invalid_fields']);
require_once dirname(__DIR__,2).'/config/session.php';if(!verifyChichejCsrfToken(is_string($body['csrf_token'])?$body['csrf_token']:null))registrationJson(403,['success'=>false,'code'=>'invalid_csrf']);
$token=is_string($body['idToken'])?$body['idToken']:'';$name=is_string($body['nombre'])?trim($body['nombre']):'';if($token===''||strlen($token)>20000||mb_strlen($name)<2||mb_strlen($name)>80)registrationJson(422,['success'=>false,'code'=>'invalid_data']);
$firebase=require dirname(__DIR__,2).'/config/firebase.php';if(($firebase['server_token_verifier_configured']??false)!==true)registrationJson(503,['success'=>false,'code'=>'server_unavailable']);require_once $firebase['autoload_path'];require_once dirname(__DIR__,2).'/includes/auth.php';require_once dirname(__DIR__,2).'/services/FirebaseReadService.php';
try{$factory=(new Factory())->withServiceAccount($firebase['service_account_path'])->withDatabaseUri($firebase['client']['databaseURL']);$verified=$factory->createAuth()->verifyIdToken($token);$uid=trim((string)$verified->claims()->get('sub'));$email=$verified->claims()->get('email','');if($uid===''||!is_string($email)||$email==='')registrationJson(401,['success'=>false,'code'=>'invalid_token']);$service=new FirebaseReadService();$profile=$service->createCustomerProfileIfMissing($uid,$name,$email);if(($profile['bloqueado']??false)===true)registrationJson(403,['success'=>false,'code'=>'account_blocked']);$role=trim(is_scalar($profile['rol']??null)?(string)$profile['rol']:'');if(!in_array($role,['cliente','admin','admin_principal'],true))registrationJson(403,['success'=>false,'code'=>'role_not_allowed']);establishVerifiedSession(['uid'=>$uid,'name'=>trim(is_scalar($profile['nombre']??null)?(string)$profile['nombre']:'')?:$name,'email'=>$email,'role'=>$role,'avatar'=>is_scalar($profile['avatarPath']??null)?(string)$profile['avatarPath']:'assets/avatares/invitado.png','blocked'=>false]);registrationJson(200,['success'=>true,'redirect'=>in_array($role,['admin','admin_principal'],true)?'admin/':'usuario/']);}catch(FailedToVerifyToken){registrationJson(401,['success'=>false,'code'=>'invalid_token']);}catch(Throwable){registrationJson(503,['success'=>false,'code'=>'profile_pending']);}
