<?php
require __DIR__.'/../includes/views/profile-ux.php'; return;
$pageTitle='Mi perfil'; $basePath='../';
require_once __DIR__.'/../includes/auth.php'; requireUser('../login.php');
$profileUser=currentUser();
$avatarName=basename((string)($profileUser['avatar']??'invitado.png'));
$profileAvatar=$avatarName==='logochichej.png'?'../assets/img/logochichej.png':'../assets/img/avatares/'.(preg_match('/^avatar[1-9]\.png$/',$avatarName)?$avatarName:'invitado.png');
require __DIR__.'/../includes/header.php'; require __DIR__.'/../includes/navbar.php';
?>
<main id="contenido" class="portal"><section class="portal-hero portal-hero--small"><div class="container"><span class="eyebrow eyebrow--light">Área de usuario</span><h1>Mi perfil</h1><p>Identidad compartida con la aplicación CHICHEJ.</p></div></section><section class="section section--cream"><div class="container profile-layout"><aside class="profile-card"><img class="profile-avatar" src="<?= htmlspecialchars($profileAvatar) ?>" alt="Avatar de <?= htmlspecialchars((string)$profileUser['name']) ?>"><span class="status-pill status-pill--active">● Sesión autenticada</span><h2><?= htmlspecialchars((string)$profileUser['name']) ?></h2><p>Perfil verificado de CHICHEJ.</p><nav aria-label="Secciones del perfil"><a class="is-active" href="#informacion">Información personal</a><a href="pedidos.php">Historial y pedidos</a><a href="reservas.php">Reservas</a><a href="promociones.php">Promociones</a><a href="#preferencias">Preferencias</a></nav></aside><div class="profile-content"><section class="profile-section" id="informacion"><div class="profile-section__head"><div><span class="eyebrow">Información personal</span><h2>Datos de la cuenta</h2></div><button class="button button--ghost" type="button" disabled>Editar</button></div><div class="profile-fields"><label>Nombre<span><?= htmlspecialchars((string)$profileUser['name']) ?></span></label><label>Correo<span><?= htmlspecialchars((string)$profileUser['email']) ?></span></label><label>Rol<span><?= htmlspecialchars((string)$profileUser['role']) ?></span></label><label>UID<span>Identidad verificada</span></label></div></section><section class="profile-section" id="preferencias"><div class="profile-section__head"><div><span class="eyebrow">Personalización</span><h2>Elige tu avatar</h2><p>Selección demostrativa; no se almacena todavía.</p></div></div><div class="avatar-picker" data-avatar-picker><?php for ($i=1; $i<=9; $i++): ?><button type="button" data-avatar-src="../assets/img/avatares/avatar<?= $i ?>.png" aria-label="Seleccionar avatar <?= $i ?>"><img src="../assets/img/avatares/avatar<?= $i ?>.png" alt="Avatar CHICHEJ <?= $i ?>" loading="lazy"></button><?php endfor; ?></div><p class="avatar-status" data-avatar-status role="status">Avatar existente cargado. La selección sigue siendo solo visual.</p></section><section class="profile-section"><div class="profile-section__head"><div><span class="eyebrow">Actividad</span><h2>Resumen personal</h2></div></div><div class="profile-stats"><div><strong>—</strong><span>Pedidos</span></div><div><strong>—</strong><span>Reservas</span></div><div><strong>—</strong><span>Promociones</span></div></div></section></div></div></section></main>
<?php require __DIR__.'/../includes/footer.php'; ?>
