<?php
declare(strict_types=1);
require_once __DIR__.'/../auth.php';requireAdmin('../login.php','../usuario/index.php');require_once __DIR__.'/../firebase-data.php';
$basePath='../';$adminScripts=true;$productScripts=true;$adminActive='productos';$pageTitle='Administración · Productos';$records=normalizeProducts(firebaseRead(fn(FirebaseReadService $f)=>$f->collection('productos')));usort($records,fn($a,$b)=>(($a['opcion']??PHP_INT_MAX)<=>($b['opcion']??PHP_INT_MAX))?:strnatcasecmp((string)$a['nombre'],(string)$b['nombre']));
$images=[];foreach(glob(dirname(__DIR__,2).'/assets/img/productos/*.{png,jpg,jpeg,webp,gif}',GLOB_BRACE)?:[] as $file)$images[]='assets/img/productos/'.basename($file);
$clientProducts=[];foreach($records as $p)$clientProducts[(string)($p['id']??$p['productoId']??'')]=['nombre'=>$p['nombre'],'descripcion'=>$p['descripcion'],'precio'=>$p['precio'],'cantidadMl'=>$p['cantidadMl'],'opcion'=>$p['opcion'],'imagen'=>$p['imagen']??'','esGratis'=>$p['esGratis'],'activo'=>$p['activo'],'agotado'=>$p['agotado'],'bebidaId'=>$p['bebidaId']??'','tipoBebida'=>$p['tipoBebida']??''];
require __DIR__.'/../header.php';require __DIR__.'/../navbar.php';require __DIR__.'/../admin-nav.php';
?>
<main id="contenido" class="admin-page" data-product-admin data-create-endpoint="../api/admin/products/create.php" data-update-endpoint="../api/admin/products/update.php" data-status-endpoint="../api/admin/products/update-status.php" data-csrf="<?=h(chichejCsrfToken())?>">
<section class="admin-head admin-head--with-nav"><div class="container"><div><span class="eyebrow eyebrow--light">Administración · Gestión segura</span><h1>Productos</h1><p>Gestiona el catálogo sin eliminar referencias históricas.</p></div><button class="button button--outline-light" type="button" data-product-new>Nuevo producto</button></div></section>
<section class="section section--cream"><div class="container"><section class="admin-data" data-filter-scope><div class="admin-filterbar"><label class="admin-search">Buscar<input type="search" data-filter-search placeholder="Nombre, descripción, presentación…"></label><label>Publicación<select data-filter-key="active"><option value="">Todos</option><option value="si">Activos</option><option value="no">Inactivos</option></select></label><label>Disponibilidad<select data-filter-key="soldout"><option value="">Todos</option><option value="no">Disponibles</option><option value="si">Agotados</option></select></label><span data-filter-count><?=count($records)?> registros</span></div>
<?php if(!$records):?><div class="empty-state"><span>◇</span><h2>Sin productos</h2><p>No hay documentos disponibles.</p></div><?php else:?><div class="admin-scroll-list product-admin-list" tabindex="0"><?php foreach($records as $p):$id=(string)($p['id']??$p['productoId']??'');$image=safeAssetImage($p['imagen']??'','../');?><article class="admin-row product-admin-card" data-filter-row data-search="<?=h(implode(' ',[$id,$p['nombre'],$p['descripcion'],$p['cantidadMl'],$p['tipoBebida'],$p['bebidaId']]))?>" data-active="<?=$p['activo']?'si':'no'?>" data-soldout="<?=$p['agotado']?'si':'no'?>" data-product-id="<?=h($id)?>"><div class="product-admin-card__identity"><?php if($image!==''):?><img src="<?=h($image)?>" alt="" loading="lazy"><?php endif;?><div><small><?=h($id!==''?$id:'Sin ID')?></small><h2 data-product-name><?=h($p['nombre'])?></h2><p><?=h($p['descripcion'])?></p></div></div><dl><div><dt>Presentación</dt><dd><?=h($p['cantidadMl']??'—')?> ml</dd></div><div><dt>Precio</dt><dd><?=h($p['esGratis']?'Gratis':money($p['precio']))?></dd></div><div><dt>Publicación</dt><dd data-product-active-label><?=$p['activo']?'Activo':'Inactivo'?></dd></div><div><dt>Disponibilidad</dt><dd data-product-soldout-label><?=$p['agotado']?'Agotado':'Disponible'?></dd></div><div><dt>Opción</dt><dd><?=h($p['opcion']??'Sin datos')?></dd></div><div><dt>Tipo</dt><dd><?=h($p['tipoBebida']??'Sin datos')?></dd></div></dl><div class="product-card-actions"><button class="button button--primary" type="button" data-product-edit="<?=h($id)?>">Editar</button><button class="button button--ghost" type="button" data-product-status="<?=$p['activo']?'desactivar':'activar'?>"><?=$p['activo']?'Desactivar':'Activar'?></button><button class="button button--ghost" type="button" data-product-status="<?=$p['agotado']?'disponible':'agotar'?>"><?=$p['agotado']?'Marcar disponible':'Marcar agotado'?></button></div><p class="form-status" data-product-status-message role="status" aria-live="polite"></p></article><?php endforeach;?></div><p data-filter-empty hidden>No hay productos que coincidan con los filtros.</p><?php endif;?></section></div></section>
</main>
<dialog class="product-modal" data-product-form-dialog aria-labelledby="product-form-title"><form data-product-form><input type="hidden" name="productId"><div class="product-modal__head"><div><span class="eyebrow">Catálogo CHICHEJ</span><h2 id="product-form-title">Nuevo producto</h2></div><button type="button" data-product-dialog-close aria-label="Cerrar">×</button></div><div class="product-form-grid"><label>Nombre<input name="nombre" minlength="2" maxlength="120" required></label><label>Descripción<textarea name="descripcion" maxlength="600" rows="3"></textarea></label><label>Precio (Bs)<input type="number" name="precio" min="0" max="100000" step="0.01" required></label><label>Cantidad (ml)<input type="number" name="cantidadMl" min="1" max="100000" required></label><label>Opción / orden <small>Opcional</small><input type="number" name="opcion" min="0" max="10000"></label><label>Imagen local <small>Opcional</small><select name="imagen"><option value="">Sin imagen</option><?php foreach($images as $image):?><option value="<?=h($image)?>"><?=h(basename($image))?></option><?php endforeach;?></select></label><label>Bebida ID <small>Opcional</small><input name="bebidaId" maxlength="100" pattern="[A-Za-z0-9_-]*"></label><label>Tipo de bebida <small>Opcional</small><input name="tipoBebida" maxlength="80"></label><label class="check"><input type="checkbox" name="esGratis"> Producto gratuito</label><label class="check"><input type="checkbox" name="activo" checked> Activo en catálogo</label><label class="check"><input type="checkbox" name="agotado"> Agotado</label></div><p class="form-status" data-product-form-status role="status" aria-live="polite"></p><div class="product-modal__actions"><button class="button button--ghost" type="button" data-product-dialog-close>Cancelar</button><button class="button button--primary" type="submit">Guardar producto</button></div></form></dialog>
<script type="application/json" id="product-admin-data"><?=json_encode($clientProducts,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?></script>
<?php require __DIR__.'/../footer.php';?>
