<?php
$pageTitle='Productos'; $activePage='productos'; $basePath=''; require_once __DIR__.'/../firebase-data.php';
$catalog=normalizeProducts(firebaseRead(fn(FirebaseReadService $f)=>$f->collection('productos')));
$catalog=array_values(array_filter($catalog,fn(array $p)=>$p['activo']));
usort($catalog,fn(array $a,array $b)=>(int)($a['opcion']??0)<=>(int)($b['opcion']??0));
$messages=firebaseRead(fn(FirebaseReadService $f)=>$f->collection('mensajes')); $activePromotion=null;
foreach($messages as $message) if(is_array($message)&&($message['activo']??false)===true&&($message['tipo']??'')==='promocion'){$activePromotion=$message;break;}
require __DIR__.'/../header.php'; require __DIR__.'/../navbar.php';
?>
<main id="contenido"><section class="page-hero page-hero--products"><div class="container"><span class="eyebrow eyebrow--light">Nuestro catálogo</span><h1>Un tamaño para cada <em>momento.</em></h1><p>Catálogo oficial sincronizado con CHICHEJ. La compra web todavía no está habilitada.</p></div></section><section class="section"><div class="container"><?php if(!$catalog):?><div class="empty-state"><span>◇</span><h2>Catálogo temporalmente no disponible</h2><p>No mostramos productos ficticios.</p></div><?php else:?><div class="catalog-grid"><?php foreach($catalog as $i=>$p):$image=safeAssetImage($p['imagen']??'');?><article class="catalog-card reveal"><div class="catalog-card__image<?=$image===''?' catalog-card__image--missing':''?>"><span><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></span><?php if($image!==''):?><img src="<?=h($image)?>" alt="<?=h($p['nombre']??'Producto CHICHEJ')?>" loading="lazy"><?php else:?><p role="img" aria-label="Imagen no disponible">Imagen no disponible</p><?php endif;?></div><div><small><?=h(($p['cantidadMl']??'').' ml')?></small><h2><?=h($p['nombre']??'Producto CHICHEJ')?></h2><p><?=h($p['descripcion']??'')?></p><div class="data-card__meta"><b><?=h(($p['esGratis']??false)?'Gratis':money($p['precio']??null))?></b><span><?=($p['agotado']??false)?'Agotado':'Disponible'?></span></div></div></article><?php endforeach;?></div><?php endif;?></div></section><section class="section section--cream promotions-showcase" id="promociones"><div class="container"><div class="promotions-showcase__heading"><div><span class="eyebrow">Promociones</span><h2>Beneficios con identidad.</h2></div><div><?php if($activePromotion):?><span class="status-pill status-pill--active">● Promoción vigente</span><h3><?=h($activePromotion['titulo']??'Promoción CHICHEJ')?></h3><p><?=h($activePromotion['mensaje']??'')?></p><?php else:?><p>No hay una promoción activa confirmada. Se conservan las campañas gráficas existentes.</p><?php endif;?></div></div><?php require __DIR__.'/../promotions-carousel.php';?></div></section></main>
<?php require __DIR__.'/../footer.php'; ?>
