<?php
$pageTitle='Mi perfil';$basePath='../';require_once __DIR__.'/../auth.php';requireUser('../login.php');require_once __DIR__.'/../firebase-data.php';$sessionUser=currentUser();$uid=(string)$sessionUser['uid'];
$profile=firebaseRead(fn(FirebaseReadService $f)=>$f->rtdb('usuarios/'.$uid));if(!is_array($profile))$profile=[];
$rawOrders=firebaseRead(fn(FirebaseReadService $f)=>$f->collection('pedidos'));$orders=array_values(array_filter($rawOrders,fn($o)=>is_array($o)&&(string)($o['usuarioId']??'')===$uid));
$rawReservations=firebaseRead(fn(FirebaseReadService $f)=>$f->collection('reservas'));$reservations=array_values(array_filter($rawReservations,fn($r)=>is_array($r)&&(string)($r['usuarioId']??'')===$uid));
$rawPromos=firebaseRead(fn(FirebaseReadService $f)=>$f->collection('mensajes'));$promos=array_values(array_filter($rawPromos,fn($m)=>is_array($m)&&($m['activo']??false)===true&&($m['tipo']??'')==='promocion'));
$validPurchases=count(array_filter($orders,'isValidSale'));$progress=customerProgress($rawOrders,$uid);$avatarName=basename(is_scalar($profile['avatarPath']??null)?(string)$profile['avatarPath']:(string)($sessionUser['avatar']??'invitado.png'));$profileAvatar='../assets/img/avatares/'.(preg_match('/^avatar[1-9]\.png$/',$avatarName)?$avatarName:'invitado.png');$firebaseConfig=require __DIR__.'/../../config/firebase.php';$accountEmail=is_scalar($profile['email']??null)?trim((string)$profile['email']):trim((string)($sessionUser['email']??''));$passwordResetEnabled=($firebaseConfig['authentication_enabled']??false)===true&&$accountEmail!=='';$phone=is_scalar($profile['telefono']??null)?trim((string)$profile['telefono']):'';
require __DIR__.'/../header.php';require __DIR__.'/../navbar.php';
?>
<main id="contenido" class="portal"><section class="portal-hero portal-hero--small"><div class="container"><span class="eyebrow eyebrow--light">Área privada</span><h1>Mi perfil</h1><p>Identidad compartida y actividad real de tu cuenta CHICHEJ.</p></div></section><section class="section section--cream"><div class="container profile-layout"><aside class="profile-card"><img class="profile-avatar" src="<?=h($profileAvatar)?>" alt="Avatar de <?=h($profile['nombre']??$sessionUser['name'])?>"><span class="status-pill status-pill--active">● <?=($profile['bloqueado']??false)?'Bloqueado':'Activo'?></span><h2><?=h($profile['nombre']??$sessionUser['name'])?></h2><p><?=h($profile['rol']??$sessionUser['role'])?></p><nav aria-label="Secciones del perfil"><a class="is-active" href="#informacion">Información personal</a><a href="#progreso">Actividad y progreso</a><a href="#preferencias">Avatar</a><a href="#seguridad">Seguridad</a><a href="pedidos.php">Pedidos</a><a href="reservas.php">Reservas</a></nav></aside><div class="profile-content">
<section class="profile-section" id="informacion"><div class="profile-section__head"><div><span class="eyebrow">Datos personales</span><h2>Editar perfil</h2><p>Solo nombre, teléfono y avatar. Correo, UID, rol y bloqueo permanecen protegidos.</p></div></div><form class="profile-edit-preview" data-profile-form data-profile-endpoint="../api/user/profile-update.php"><input type="hidden" name="csrf_token" value="<?=h(chichejCsrfToken())?>"><input type="hidden" name="avatarPath" value="assets/avatares/<?=h(preg_match('/^avatar[1-9]\.png$/',$avatarName)?$avatarName:'invitado.png')?>"><label>Nombre<input name="nombre" value="<?=h($profile['nombre']??$sessionUser['name'])?>" minlength="2" maxlength="80" required></label><label>Teléfono<input name="telefono" value="<?=h($phone)?>" maxlength="20" inputmode="tel" placeholder="Opcional"></label><label>Correo<input value="<?=h($accountEmail)?>" disabled></label><label>Rol<input value="<?=h($profile['rol']??$sessionUser['role'])?>" disabled aria-describedby="protected-fields"></label><button class="button button--primary" type="submit">Guardar cambios</button><p id="protected-fields">No se aceptarán campos administrativos ni un UID enviado por el navegador.</p><p class="form-status" data-profile-status role="status" aria-live="polite"></p></form></section>
<section class="profile-section" id="progreso"><div class="profile-section__head"><div><span class="eyebrow">Tu progreso este mes</span><h2>Metas CHICHEJ</h2></div></div><div class="progress-grid"><article><span>Cliente del mes</span><strong><?=$progress['monthlyPurchases']?> / 5</strong><p>Realiza 5 compras durante el mes.</p><i style="--progress:<?=min(100,round($progress['monthlyPurchases']/5*100))?>%"></i><b><?=$progress['monthlyPurchases']>=5?'Meta alcanzada':'En progreso'?></b></article><article><span>Fan de CHICHEJ</span><strong><?=$progress['beverages']?> / 10</strong><p>Registra 10 bebidas válidas en tu historial.</p><i style="--progress:<?=min(100,round($progress['beverages']/10*100))?>%"></i><b><?=$progress['beverages']>=10?'Meta alcanzada':'En progreso'?></b></article><article><span>Consumo del mes</span><strong><?=$progress['monthlyMl']?> ml</strong><p><?=h(number_format($progress['monthlyLiters'],2,'.',''))?> litros acumulados</p><b>Datos de compras válidas</b></article></div></section>
<section class="profile-section" id="preferencias"><div class="profile-section__head"><div><span class="eyebrow">Avatar</span><h2>Elige tu identidad visual</h2><p>La selección se guardará junto con los datos personales.</p></div></div><div class="avatar-picker"><?php for($i=1;$i<=9;$i++):?><button type="button" data-avatar-src="../assets/img/avatares/avatar<?=$i?>.png" data-avatar-value="assets/avatares/avatar<?=$i?>.png" aria-label="Seleccionar avatar <?=$i?>"><img src="../assets/img/avatares/avatar<?=$i?>.png" alt="Avatar CHICHEJ <?=$i?>" loading="lazy"></button><?php endfor;?></div><p class="avatar-status" data-avatar-status role="status">Selecciona un avatar y guarda los cambios.</p></section>
<section class="profile-section" id="seguridad"><div class="profile-section__head"><div><span class="eyebrow">Firebase Authentication</span><h2>Seguridad de la cuenta</h2><p>CHICHEJ nunca solicita ni almacena tu contraseña en PHP.</p></div></div><button class="button button--primary" type="button" data-password-reset data-password-reset-email="<?=h($accountEmail)?>" <?=$passwordResetEnabled?'':'disabled'?>>Enviar enlace para restablecer contraseña</button><p class="form-status" data-password-reset-status role="status" aria-live="polite"><?=$passwordResetEnabled?'Se enviará mediante Firebase solo después de tu confirmación.':'Firebase Authentication o el correo de la cuenta no está disponible en este entorno.'?></p></section>
</div></div></section></main>
<?php require __DIR__.'/../footer.php';?>
