<?php
require_once __DIR__.'/../auth.php'; requireUser('../login.php'); require_once __DIR__.'/../firebase-data.php';
$user=currentUser(); $uid=(string)$user['uid']; $basePath='../';
if($userDataPage==='pedidos'){$pageTitle='Mis pedidos';$records=firebaseRead(fn(FirebaseReadService $f)=>array_values(array_filter($f->collection('pedidos'),fn(array $r)=>(string)($r['usuarioId']??'')===$uid)));}
elseif($userDataPage==='reservas'){$pageTitle='Mis reservas';$records=firebaseRead(fn(FirebaseReadService $f)=>array_values(array_filter($f->collection('reservas'),fn(array $r)=>(string)($r['usuarioId']??'')===$uid)));}
else{$pageTitle='Mis promociones';$records=firebaseRead(fn(FirebaseReadService $f)=>array_values(array_filter($f->collection('mensajes'),fn(array $r)=>($r['activo']??false)===true)));}
usort($records,fn(array $a,array $b)=>(firebaseDate($b['fechaCreacion']??null)?->getTimestamp()??0)<=>(firebaseDate($a['fechaCreacion']??null)?->getTimestamp()??0));
require __DIR__.'/../header.php'; require __DIR__.'/../navbar.php';
?>
<main id="contenido" class="portal"><section class="portal-hero portal-hero--small"><div class="container"><span class="eyebrow eyebrow--light">Área privada</span><h1><?=h($pageTitle)?></h1><p>Información real asociada exclusivamente a tu identidad autenticada.</p></div></section><section class="section section--cream"><div class="container"><?php if(!$records):?><div class="empty-state"><span>◇</span><h2>Sin datos registrados</h2><p>No encontramos información asociada a tu cuenta.</p></div><?php else:?><div class="data-list"><?php foreach($records as $r):?><article class="data-card"><?php if($userDataPage==='pedidos'):?><div class="data-card__head"><div><small>Pedido <?=h($r['pedidoId']??$r['_id'])?></small><h2><?=h(orderSummary($r))?></h2></div><span><?=h($r['estado']??'Sin estado')?></span></div><dl><div><dt>Fecha</dt><dd><?=h(displayDate($r['fechaCreacion']??null))?></dd></div><div><dt>Total</dt><dd><?=h(money($r['total']??null))?></dd></div><div><dt>Pago</dt><dd><?=h($r['metodoPago']??'Sin datos')?> · <?=h($r['estadoPago']??'Sin datos')?></dd></div><div><dt>Origen</dt><dd><?=h(orderOrigin($r))?></dd></div></dl><?php elseif($userDataPage==='reservas'):?><div class="data-card__head"><div><small>Reserva <?=h($r['reservaId']??$r['_id'])?></small><h2><?=h($r['detalle']??'Reserva CHICHEJ')?></h2></div><span><?=h($r['estado']??'Sin estado')?></span></div><dl><div><dt>Fecha solicitada</dt><dd><?=h(displayDate($r['fechaSolicitada']??null))?></dd></div><div><dt>Cantidad</dt><dd><?=h($r['cantidadSolicitada']??$r['cantidad']??'Sin datos')?></dd></div><div><dt>Lugar</dt><dd><?=h($r['lugarEvento']??'Sin datos')?></dd></div></dl><?php else:?><span class="eyebrow"><?=($r['tipo']??'informativo')==='promocion'?'Promoción':'Informativo'?></span><h2><?=h($r['titulo']??'Publicación CHICHEJ')?></h2><p><?=h($r['mensaje']??'')?></p><small><?=h(displayDate($r['fechaCreacion']??null))?></small><?php endif;?></article><?php endforeach;?></div><?php endif;?></div></section></main>
<?php require __DIR__.'/../footer.php'; ?>
